### ISSUE TITLE
Feature request: Include label attribute into xtable header

### ISSUE THREAD

**Issue by instantkaffee** [sjPlot/sjmisc#19]
I raised above question recently in SO.
I collaborated with the xtable maintainer to work out a solution which is posted as answer on SO.
Would it not be better to include this functionality into sjmisc package ?

http://stackoverflow.com/questions/34692402/include-label-attribute-into-xtable-header/34705889#34705889

**Comment by sjPlot** [comment]
I'm not quite sure, because **sjmisc** is not intended to print table outputs or to create latex/md-tables.

Perhaps the sjmisc-package is the right package for other packages' generic print/output functions of labelled data frames. What did the xtable maintainer say? Is he willing to implement such a print function?

For me, the problem is implementing print-/output-methods for different packages because I probably don't use these packages and thus don't know how a print-method should work... If you already have a working solution that I can use, it's of course much easier for me.

**Comment by instantkaffee** [comment]
OK, well understood. Thx.

**Comment by sjPlot** [comment]
Ok, I'm not sure, but I think I can't add such a function to my package, because `toLatex` is in the xtable-package's NameSpace. I tried to write a toLatex for `lbl_df`classes, however, the CRAN check won't work. Not sure whether I can write S3-generic-functions for other packages? I would suggest contacting the xtable-maintainer and ask him, if he could add the `toLatex.lbl_df` function to support `lbl_df` data frames.

**Comment by instantkaffee** [comment]
Really appreciate your efforts.
I raised attention of David Scott (xtable maintainer) to this conversion. Thx.
