### ISSUE TITLE
set_labels doesn't properly set labels on factor

### ISSUE THREAD

**Issue by adamryczkowski** [sjPlot/sjmisc#49]
```
x<-factor(rep(c(1,2),10)) 
y<-set_labels(x, labels=c('A','B'))
```

after which
```
> y
 [1] 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2
attr(,"labels")
A B 
1 2 
Levels: 1 2
```
For all the `labelled`-agnostic world `y` is still a factor with levels `1` and `2`. Is it by design, or is it a bug?

**Comment by sjPlot** [comment]
This is by design, as `set_labels()` just sets/adds label-attributes. If you want label-attributes as factor levels, you can use `to_label()`, which converts any input into factor and uses label-attributes as factor levels.

```
to_label(y)
#> [1] A B A B A B A B A B A B A B A B A B A B
#> Levels: A B
```

Factors with character levels are also recognized by `get_labels()`:

```
get_labels(to_label(y))
#> [1] "A" "B"
```

See vignette _Labelled Data and the sjmisc-Package_, paragraph _Value Labels_, subsection _Getting value labels_.
