### ISSUE TITLE
Warning in set_na

### ISSUE THREAD

**Issue by methodds** [sjPlot/sjmisc#51]
Hi,

I get a warning for trying to use ``set_na`` on a dataframe:

```
library(tidyverse)
library(sjPlot)
library(sjmisc)
setwd("/home/cs/Dropbox/Lehre/Methoden der politischen Soziologie/0 Daten/GLES Vorwahl")
d <- read_stata('GLES_Vorwahlquerschnitt_ZA5700_v1-0-0.dta')

d <- set_na(d, value = -99:-71)

no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "x". Infinite value range.no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "x". Infinite value range.no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "x". Infinite value range.no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "x". Infinite value range.no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfCan't set value labels for "x". Infinite value range.
```
Is this because not every variable contains values between -99 and -71?

**Comment by sjPlot** [comment]
> Is this because not every variable contains values between -99 and -71?

No, some variables only contained variables with values between -99 and -71, and all were set to `NA` - and then `set_na()` tried to set remaining value labels to a vector, which completely contained `NA`. This caused the warning, because `set_na()` called `remove_labels()`, which called `set_labels()` :-)
Now I directly set the labels-attribute, and there's no longer a warning.

**Comment by methodds** [comment]
Aah okay, thanks for the fix :)
